//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ich.Saas.Core.Code.Localization {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class SharedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal SharedResources() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ich.Saas.Core.Code.Localization.SharedResources", typeof(SharedResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Alias.
        /// </summary>
        public static string Alias {
            get {
                return ResourceManager.GetString("Alias", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Birth Date.
        /// </summary>
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Contact Email.
        /// </summary>
        public static string ContactEmail {
            get {
                return ResourceManager.GetString("ContactEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Contact Person.
        /// </summary>
        public static string ContactPerson {
            get {
                return ResourceManager.GetString("ContactPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Course.
        /// </summary>
        public static string CourseNumber {
            get {
                return ResourceManager.GetString("CourseNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Created.
        /// </summary>
        public static string CreatedDate {
            get {
                return ResourceManager.GetString("CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Full Time.
        /// </summary>
        public static string FullTime {
            get {
                return ResourceManager.GetString("FullTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Hire Date.
        /// </summary>
        public static string HireDate {
            get {
                return ResourceManager.GetString("HireDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Full Time.
        /// </summary>
        public static string IsFulltime {
            get {
                return ResourceManager.GetString("IsFulltime", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Courses.
        /// </summary>
        public static string TotalCourses {
            get {
                return ResourceManager.GetString("TotalCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Enrollments.
        /// </summary>
        public static string TotalEnrollments {
            get {
                return ResourceManager.GetString("TotalEnrollments", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Students.
        /// </summary>
        public static string TotalStudents {
            get {
                return ResourceManager.GetString("TotalStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Users.
        /// </summary>
        public static string TotalUsers {
            get {
                return ResourceManager.GetString("TotalUsers", resourceCulture);
            }
        }
    }
}
